"""
Повна колода Таро (78 карт) для бота "Карти й Шлях".
Усі трактування — авторський короткий виклад традиційної символіки карт.
"""

MAJOR_ARCANA = [
    {"name": "Блазень", "upright": "Новий початок, свобода вибору, крок у невідоме без страху. Час довіритись потоку і спробувати те, на що раніше не наважувались.", "reversed": "Необдуманий ризик, розкиданість, страх зробити перший крок. Варто зупинитись і подумати, перш ніж діяти.", "image": "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg"},
    {"name": "Маг", "upright": "У тебе вже є всі ресурси для дії. Час перетворити намір на конкретний результат.", "reversed": "Розпорошена енергія, маніпуляції або невпевненість у власних силах.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg"},
    {"name": "Верховна Жриця", "upright": "Інтуїція знає більше, ніж логіка. Дослухайся до внутрішнього голосу, не поспішай з висновками.", "reversed": "Ігнорування інтуїції, приховані мотиви, інформація, яку варто перевірити ще раз.", "image": "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg"},
    {"name": "Імператриця", "upright": "Достаток, турбота, творчий розквіт. Період, коли варіант росте сам, якщо його підживлювати.", "reversed": "Перевтома від турботи про інших, застій у творчості, залежність від зовнішнього схвалення.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg"},
    {"name": "Імператор", "upright": "Структура, контроль, стабільність. Час будувати системи та встановлювати чіткі правила.", "reversed": "Надмірний контроль, ригідність, конфлікт із авторитетом.", "image": "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg"},
    {"name": "Ієрофант", "upright": "Традиція, навчання, перевірені шляхи. Варто спертись на досвід і правила, що вже працюють.", "reversed": "Бунт проти системи, догматизм або пошук власного нестандартного шляху.", "image": "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg"},
    {"name": "Закохані", "upright": "Вибір, що ґрунтується на цінностях. Гармонія у стосунках або важливе рішення щодо союзу.", "reversed": "Внутрішній конфлікт цінностей, нерівність у стосунках, невдалий вибір.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg"},
    {"name": "Колісниця", "upright": "Рух вперед завдяки волі й дисципліні. Перемога через зосередженість на меті.", "reversed": "Втрата напрямку, боротьба протилежних сил всередині, відсутність контролю.", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg"},
    {"name": "Сила", "upright": "Внутрішня сила через м'якість і терпіння, а не тиск. Впоратись зі складним через спокій.", "reversed": "Сумніви у собі, спроба контролювати силою там, де потрібна витримка.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg"},
    {"name": "Пустельник", "upright": "Час для усамітнення й пошуку відповідей всередині себе. Мудрість приходить через паузу.", "reversed": "Ізоляція, що виснажує, або страх залишитись наодинці з думками.", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg"},
    {"name": "Колесо Фортуни", "upright": "Поворотний момент, зміна циклу. Те, що відбувається зараз, — частина більшого руху.", "reversed": "Відчуття, що все йде не за планом, опір неминучим змінам.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg"},
    {"name": "Справедливість", "upright": "Причина і наслідок. Чесність із собою та іншими принесе баланс.", "reversed": "Несправедливість, ухилення від відповідальності, викривлене бачення ситуації.", "image": "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg"},
    {"name": "Повішений", "upright": "Пауза, погляд на ситуацію під іншим кутом. Іноді бездіяльність — це і є правильна дія.", "reversed": "Затягнута жертовність без сенсу, відчуття застрягання.", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg"},
    {"name": "Смерть", "upright": "Завершення одного етапу, щоб звільнити місце для нового. Трансформація, а не буквальний кінець.", "reversed": "Опір неминучим змінам, страх відпустити старе.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg"},
    {"name": "Помірність", "upright": "Баланс, поєднання протилежностей, терпіння. Поступовий прогрес дає стійкий результат.", "reversed": "Крайнощі, втрата рівноваги, нетерплячість.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg"},
    {"name": "Диявол", "upright": "Залежність, ілюзія обмежень, спокуса. Варто побачити, де ти сам створюєш собі клітку.", "reversed": "Звільнення від шкідливого патерну, усвідомлення власної влади над ситуацією.", "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg"},
    {"name": "Вежа", "upright": "Раптове руйнування старої структури, яке відкриває правду. Криза, що веде до оновлення.", "reversed": "Уникнення неминучого краху, страх перед змінами, що насправді потрібні.", "image": "https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg"},
    {"name": "Зірка", "upright": "Надія, натхнення, відновлення після кризи. Віра у краще майбутнє має підстави.", "reversed": "Втрата віри, розчарування, вигорання.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg"},
    {"name": "Місяць", "upright": "Невизначеність, підсвідомі страхи, ілюзії. Не все видно чітко — довірся часу.", "reversed": "Прояснення після періоду тривоги, викриття прихованого обману.", "image": "https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg"},
    {"name": "Сонце", "upright": "Радість, ясність, успіх. Період відкритості та щирого задоволення від життя.", "reversed": "Тимчасова затримка радості, надмірний оптимізм, що ігнорує реальність.", "image": "https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg"},
    {"name": "Суд", "upright": "Пробудження, підбиття підсумків, друга спроба. Час зробити висновки з минулого досвіду.", "reversed": "Самокритика, страх бути оціненим, небажання зробити висновки.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg"},
    {"name": "Світ", "upright": "Завершення великого циклу, цілісність, досягнення мети. Все стає на свої місця.", "reversed": "Незавершеність, відчуття, що чогось бракує для повного закриття етапу.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg"},
]

MINOR_ARCANA = [
    # --- Жезли (вогонь: дія, пристрасть, кар'єра) ---
    {"name": "Туз Жезлів", "upright": "Нова іскра натхнення та енергії для дії. Ідеальний момент розпочати проєкт.", "reversed": "Затримка старту, вигорання ще до початку, брак мотивації.", "image": "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg"},
    {"name": "Двійка Жезлів", "upright": "Планування майбутнього, вибір напрямку розвитку. Час дивитись за межі звичного.", "reversed": "Страх вийти за межі комфорту, нерішучість щодо великих планів.", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg"},
    {"name": "Трійка Жезлів", "upright": "Перші результати роботи вже видно, час розширювати горизонти.", "reversed": "Затримки в реалізації планів, недооцінка перешкод попереду.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg"},
    {"name": "Четвірка Жезлів", "upright": "Святкування досягнення, стабільність і радість від пройденого етапу.", "reversed": "Нестабільність вдома чи в команді, відкладене святкування.", "image": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg"},
    {"name": "П'ятірка Жезлів", "upright": "Конкуренція та суперечки, які загартовують і виявляють сильніших.", "reversed": "Виснажливий конфлікт без переможця, внутрішня боротьба.", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg"},
    {"name": "Шістка Жезлів", "upright": "Визнання успіху, перемога після зусиль стає публічною.", "reversed": "Затримане визнання, страх виставити свої досягнення напоказ.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg"},
    {"name": "Сімка Жезлів", "upright": "Захист своєї позиції під тиском конкурентів чи критики.", "reversed": "Виснаження від постійної оборони, сумніви у власній правоті.", "image": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg"},
    {"name": "Вісімка Жезлів", "upright": "Швидкий рух подій, новини та рішення надходять стрімко.", "reversed": "Затримки, розлад у комунікації, все відбувається повільніше очікуваного.", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg"},
    {"name": "Дев'ятка Жезлів", "upright": "Стійкість перед останнім випробуванням, сили ще є для фінального ривка.", "reversed": "Виснаження, готовність здатись за крок до фінішу.", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg"},
    {"name": "Десятка Жезлів", "upright": "Тягар відповідальності через власний успіх, час делегувати частину.", "reversed": "Перевантаження, відмова просити допомоги, ризик вигорання.", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg"},
    {"name": "Паж Жезлів", "upright": "Нова цікава ідея чи звістка, що запалює ентузіазм.", "reversed": "Непослідовність, ідеї без реалізації, поспішні рішення.", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg"},
    {"name": "Лицар Жезлів", "upright": "Рішучий рух до мети, сміливість і пристрасть у дії.", "reversed": "Імпульсивність, поспіх, ризик діяти необдумано.", "image": "https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg"},
    {"name": "Королева Жезлів", "upright": "Впевненість, харизма, здатність надихати інших власним прикладом.", "reversed": "Надмірна конкурентність, ревнощі, потреба постійного визнання.", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg"},
    {"name": "Король Жезлів", "upright": "Лідерство через бачення і сміливість, здатність вести за собою.", "reversed": "Деспотичність, надмірні амбіції, ігнорування думки інших.", "image": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg"},

    # --- Кубки (вода: емоції, стосунки, інтуїція) ---
    {"name": "Туз Кубків", "upright": "Нове почуття, емоційне відкриття, початок глибокого зв'язку.", "reversed": "Заблоковані емоції, розчарування чи емоційна порожнеча.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg"},
    {"name": "Двійка Кубків", "upright": "Взаємний зв'язок, партнерство на рівних, гармонія у стосунках.", "reversed": "Дисбаланс у стосунках, непорозуміння між двома сторонами.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg"},
    {"name": "Трійка Кубків", "upright": "Дружба, спільне святкування, підтримка близького кола.", "reversed": "Плітки, поверхневі зв'язки, конфлікт у групі друзів.", "image": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg"},
    {"name": "Четвірка Кубків", "upright": "Апатія, споглядання, час переоцінити те, що вже маєш.", "reversed": "Пробудження з апатії, готовність побачити нові можливості.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg"},
    {"name": "П'ятірка Кубків", "upright": "Смуток за втраченим, але не все втрачено, є ще на що спертися.", "reversed": "Прийняття втрати, рух далі після періоду жалю.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg"},
    {"name": "Шістка Кубків", "upright": "Ностальгія, тепла згадка минулого, підтримка зі сторони давніх зв'язків.", "reversed": "Застрягання в минулому, ідеалізація того, чого вже нема.", "image": "https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg"},
    {"name": "Сімка Кубків", "upright": "Багато варіантів і мрій, потрібно обрати реальний шлях.", "reversed": "Ілюзії розвіюються, час обрати щось одне конкретне.", "image": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg"},
    {"name": "Вісімка Кубків", "upright": "Свідомий відхід від того, що більше не наповнює сенсом.", "reversed": "Страх покинути звичне, хоча воно вже не задовольняє.", "image": "https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg"},
    {"name": "Дев'ятка Кубків", "upright": "Задоволення бажань, емоційне благополуччя, відчуття, що мрії справджуються.", "reversed": "Поверхневе задоволення, самовдоволення без справжнього щастя.", "image": "https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg"},
    {"name": "Десятка Кубків", "upright": "Родинна гармонія, емоційне завершення на найвищій ноті.", "reversed": "Розлад у сім'ї, ідеалізована картинка, що не відповідає реальності.", "image": "https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg"},
    {"name": "Паж Кубків", "upright": "Емоційна новина, чутливе і творче послання.", "reversed": "Емоційна незрілість, надмірна чутливість до критики.", "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg"},
    {"name": "Лицар Кубків", "upright": "Романтичний жест, слідування за почуттями і мрією.", "reversed": "Нещирість, обіцянки без дій, емоційні маніпуляції.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg"},
    {"name": "Королева Кубків", "upright": "Глибока емпатія, емоційна мудрість, турбота про інших.", "reversed": "Емоційна залежність, розмиті межі, надмірна чутливість.", "image": "https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg"},
    {"name": "Король Кубків", "upright": "Емоційна зрілість, спокійне лідерство через розуміння почуттів.", "reversed": "Придушені емоції, холодність, маніпуляція почуттями інших.", "image": "https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg"},

    # --- Мечі (повітря: думки, конфлікт, комунікація) ---
    {"name": "Туз Мечів", "upright": "Ясність думки, прорив розуміння, момент істини.", "reversed": "Плутанина, викривлена інформація, необдумане рішення.", "image": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg"},
    {"name": "Двійка Мечів", "upright": "Складний вибір, якого уникають, потрібно зняти пов'язку з очей.", "reversed": "Рішення більше не можна відкладати, час зробити вибір.", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg"},
    {"name": "Трійка Мечів", "upright": "Біль, розчарування, важка правда, яку потрібно прийняти.", "reversed": "Загоєння після болю, прощення себе чи інших.", "image": "https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg"},
    {"name": "Четвірка Мечів", "upright": "Відпочинок, пауза для відновлення сил перед новим етапом.", "reversed": "Вимушений відпочинок через виснаження, ігнорування потреби в паузі.", "image": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg"},
    {"name": "П'ятірка Мечів", "upright": "Перемога, що залишає гіркий присмак, конфлікт без справжніх переможців.", "reversed": "Час залишити суперечку позаду, відпустити потребу бути правим.", "image": "https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg"},
    {"name": "Шістка Мечів", "upright": "Перехід до спокійніших вод, віддалення від складного періоду.", "reversed": "Застрягання у важкому періоді, опір необхідним змінам.", "image": "https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg"},
    {"name": "Сімка Мечів", "upright": "Стратегія, обхідний шлях, іноді потрібно діяти непомітно.", "reversed": "Викриття обману, нечесність повертається бумерангом.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg"},
    {"name": "Вісімка Мечів", "upright": "Відчуття пастки, хоча вихід насправді є, обмеження здебільшого в голові.", "reversed": "Звільнення від власних обмежувальних переконань.", "image": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg"},
    {"name": "Дев'ятка Мечів", "upright": "Тривога, безсоння, страхи, що здаються більшими вночі, ніж вдень.", "reversed": "Полегшення після періоду тривоги, страхи виявляються перебільшеними.", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg"},
    {"name": "Десятка Мечів", "upright": "Болісне завершення, дно, після якого можливе лише відновлення.", "reversed": "Повільне відновлення після кризи, світло після найтемнішого моменту.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg"},
    {"name": "Паж Мечів", "upright": "Допитливість, гострий розум, новини що потребують перевірки.", "reversed": "Пліткарство, необачні слова, інформація без перевірки фактів.", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg"},
    {"name": "Лицар Мечів", "upright": "Рішучі дії та пряма комунікація, швидкий рух до мети.", "reversed": "Агресивність, необдумана прямота, конфлікт через поспіх.", "image": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg"},
    {"name": "Королева Мечів", "upright": "Чесність, ясність мислення, здатність бачити ситуацію без ілюзій.", "reversed": "Холодна різкість, критичність, що ранить замість допомогти.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg"},
    {"name": "Король Мечів", "upright": "Логіка та справедливість у прийнятті рішень, авторитет через розум.", "reversed": "Надмірна суворість, маніпуляція через слова, холодний розрахунок.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg"},

    # --- Пентаклі (земля: гроші, робота, матеріальне) ---
    {"name": "Туз Пентаклів", "upright": "Нова фінансова чи професійна можливість з хорошим потенціалом.", "reversed": "Втрачена можливість, фінансова нестабільність, невдалий старт.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg"},
    {"name": "Двійка Пентаклів", "upright": "Балансування між кількома справами чи джерелами доходу.", "reversed": "Перевантаження справами, втрата балансу між пріоритетами.", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg"},
    {"name": "Трійка Пентаклів", "upright": "Командна робота, майстерність визнана іншими, хороша співпраця.", "reversed": "Розлад у команді, брак координації, недооцінена робота.", "image": "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg"},
    {"name": "Четвірка Пентаклів", "upright": "Фінансова стабільність, але й тенденція тримати все під контролем.", "reversed": "Надмірна прив'язаність до грошей, страх втратити накопичене.", "image": "https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg"},
    {"name": "П'ятірка Пентаклів", "upright": "Фінансові труднощі чи відчуття нестачі, хоча допомога поруч.", "reversed": "Покращення після важкого періоду, відновлення ресурсів.", "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg"},
    {"name": "Шістка Пентаклів", "upright": "Щедрість, справедливий обмін, допомога що приходить у потрібний момент.", "reversed": "Нерівність в обміні, залежність від чужої милості.", "image": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg"},
    {"name": "Сімка Пентаклів", "upright": "Оцінка вкладених зусиль, час подивитись, чи варто продовжувати.", "reversed": "Нетерплячість щодо результатів, відчуття втраченого часу.", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg"},
    {"name": "Вісімка Пентаклів", "upright": "Наполеглива праця та вдосконалення майстерності приносять плоди.", "reversed": "Недбала робота, брак мотивації вдосконалюватись.", "image": "https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg"},
    {"name": "Дев'ятка Пентаклів", "upright": "Незалежність та задоволення від власних досягнень.", "reversed": "Надмірна ізоляція заради роботи, фінансова залежність від інших.", "image": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg"},
    {"name": "Десятка Пентаклів", "upright": "Довготривала стабільність, спадщина, матеріальне благополуччя родини.", "reversed": "Фінансові суперечки в родині, нестабільна спадщина.", "image": "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg"},
    {"name": "Паж Пентаклів", "upright": "Нова можливість навчання чи заробітку, практичний початок.", "reversed": "Відсутність дисципліни, нереалістичні фінансові плани.", "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg"},
    {"name": "Лицар Пентаклів", "upright": "Методичність, надійність, повільний та стабільний прогрес.", "reversed": "Застій через страх ризикувати, надмірна обережність.", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg"},
    {"name": "Королева Пентаклів", "upright": "Практична турбота, вміння поєднувати роботу і затишок вдома.", "reversed": "Перевантаження побутовими турботами, знехтуване самопіклування.", "image": "https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg"},
    {"name": "Король Пентаклів", "upright": "Фінансова мудрість, стабільність через дисципліновану працю.", "reversed": "Матеріалізм, надмірна прив'язаність до статусу і грошей.", "image": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg"},
]

FULL_DECK = MAJOR_ARCANA + MINOR_ARCANA  # 78 карт разом
